services:
  noet:
    image: ghcr.io/rishikanthc/noet:v0.3.0
    restart: unless-stopped
    networks:
      - caddy-stack_caddy_net
    volumes:
      - ./data:/data
    environment:
      - NOET_DB_PATH=/data/noet.db
      - CORS_ALLOWED_ORIGINS=https://kindled.dev
    labels:
      # Domain with proper SSE handling
      caddy: kindled.dev
      caddy.reverse_proxy: "{{upstreams 8081}}"

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/api/settings"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  caddy-stack_caddy_net:
    external: true
